# Generated by Django 4.1.7 on 2023-08-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("borough", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="uploads/areaimg/default.png",
                        null=True,
                        upload_to="uploads/areaimg",
                    ),
                ),
                ("homeless_sightings", models.IntegerField(blank=True, default=0)),
                ("litter_count", models.IntegerField(blank=True, default=0)),
                ("swearing_count", models.IntegerField(blank=True, default=0)),
                ("cig_but_count", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ratings.area"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
